const epIcon = "https://static.wikia.nocookie.net/clashofclans/images"

export const iconUrls = {
    /*============== tropas normais ==============================*/
    Barbarian: `${epIcon}/8/87/Avatar_Barbarian.png`,
    Archer: `${epIcon}/6/68/Avatar_Archer.png`,
    Goblin: `${epIcon}/6/68/Avatar_Goblin.png`,
    Giant: `${epIcon}/7/7d/Avatar_Giant.png`,
    "Wall Breaker": `${epIcon}/3/36/Avatar_Wall_Breaker.png`,
    Balloon: `${epIcon}/8/80/Avatar_Balloon.png`,
    Wizard: `${epIcon}/9/97/Avatar_Wizard.png`,
    Healer: `${epIcon}/9/9c/Avatar_Healer.png`,
    Dragon: `${epIcon}/9/9c/Avatar_Dragon.png`,
    "P.E.K.K.A": `${epIcon}/1/1a/Avatar_P.E.K.K.A.png`,
    Minion: `${epIcon}/6/6d/Avatar_Minion.png`,
    "Hog Rider": `${epIcon}/5/5d/Avatar_Hog_Rider.png`,
    Valkyrie: `${epIcon}/3/39/Avatar_Valkyrie.png`,
    Golem: `${epIcon}/f/f5/Avatar_Golem.png`,
    "Baby Dragon": `${epIcon}/7/7a/Avatar_Baby_Dragon.png`,
    "Miner": `${epIcon}/7/7a/Avatar_Miner.png`,
    "Electro Dragon": `${epIcon}/9/97/Avatar_Electro_Dragon.png`,
    "Yeti": `${epIcon}/b/be/Avatar_Yeti.png`,
    "Dragon Rider": `${epIcon}/5/50/Avatar_Dragon_Rider.png`,
    "Electro Titan": `${epIcon}/6/67/Avatar_Electro_Titan.png`,
    "Root Rider": `${epIcon}/0/0b/Avatar_Root_Rider.png`,
    "Thrower": `${epIcon}/d/da/Avatar_Thrower.png`,
    "Minion": `${epIcon}/3/3b/Avatar_Minion.png`,
    "Hog Rider": `${epIcon}/e/e9/Avatar_Hog_Rider.png`,
    "Valkyrie": `${epIcon}/3/31/Avatar_Valkyrie.png`,
    "Golem": `${epIcon}/4/44/Avatar_Golem.png`,
    "Witch": `${epIcon}/9/90/Avatar_Witch.png`,
    "Lava Hound": `${epIcon}/1/1b/Avatar_Lava_Hound.png`,
    "Bowler": `${epIcon}/2/24/Avatar_Bowler.png`,
    "Ice Golem": `${epIcon}/7/79/Avatar_Ice_Golem.png`,
    "Headhunter": `${epIcon}/8/80/Avatar_Headhunter.png`,
    "Apprentice Warden": `${epIcon}/8/8b/Avatar_Apprentice_Warden.png`,
    "Druid": `${epIcon}/4/43/Avatar_Druid.png`,
    "Wall Wrecker": `${epIcon}/f/f3/Avatar_Wall_Wrecker.png/`,
    "Battle Blimp": `${epIcon}/2/2f/Avatar_Battle_Blimp.png/`,
    "Stone Slammer": `${epIcon}/a/ad/Avatar_Stone_Slammer.png/`,
    "Battle Drill": `${epIcon}/9/99/Avatar_Battle_Drill.png/`,
    "Super Barbarian": `${epIcon}/8/81/Avatar_Super_Barbarian.png/`,
    "Super Archer": `${epIcon}/3/3a/Avatar_Super_Archer.png/`,
    "Super Giant": `${epIcon}/6/6b/Avatar_Super_Giant.png/`,
    "Sneaky Goblin": `${epIcon}/6/6e/Avatar_Sneaky_Goblin.png/`,
    "Super Wall Breaker": `${epIcon}/c/ca/Avatar_Super_Wall_Breaker.png/`,
    "Rocket Balloon": `${epIcon}/e/ed/Avatar_Rocket_Balloon.png/`,
    "Super Wizard": `${epIcon}/f/f9/Avatar_Super_Wizard.png/`,
    /*============== Super tropas ==============================*/
    "Super Dragon": `${epIcon}/0/0f/Avatar_Super_Dragon.png/`,
    "Inferno Dragon": `${epIcon}/0/0b/Avatar_Inferno_Dragon.png/`,
    "Super Miner": `${epIcon}/b/b3/Avatar_Super_Miner.png/`,
    "Super Minion": `${epIcon}/b/be/Avatar_Super_Minion.png/`,
    "Super Hog Rider": `${epIcon}/c/c4/Avatar_Super_Hog_Rider.png/`,
    "Super Valkyrie": `${epIcon}/9/9e/Avatar_Super_Valkyrie.png/`,
    "Super Witch": `${epIcon}/1/18/Avatar_Super_Witch.png/`,
    "Ice Hound": `${epIcon}/b/b0/Avatar_Ice_Hound.png/`,
    "Super Bowler": `${epIcon}/3/39/Avatar_Super_Bowler.png/`,
    /*============== Heróis - https://clashofclans.fandom.com/wiki/Heroes ================*/
    /*============== Feitiços - https://clashofclans.fandom.com/wiki/Elixir_Spells - https://clashofclans.fandom.com/wiki/Dark_Spells ================*/
    
    



    // Adicione outros ícones aqui
  };

  const translatedNames = {
    Barbarian: "Bárbaro",
    Archer: "Arqueira",
    Goblin: "Goblin",
    Giant: "Gigante",
    "Wall Breaker": "Quebra-Muros",
    Balloon: "Balão",
    Wizard: "Mago",
    Healer: "Curadora",
    Dragon: "Dragão",
    "P.E.K.K.A": "P.E.K.K.A",
    Minion: "Serva",
    "Hog Rider": "Corredor",
    Valkyrie: "Valquíria",
    Golem: "Golem",
    "Super Barbarian": "Super Bárbaro",
    "Super Archer": "Super Arqueira",
    "Super Giant": "Super Gigante",
    "Sneaky Goblin": "Goblin Furtivo",
    "Super Wall Breaker": "Super Quebra-Muros",
    "Rocket Balloon": "Balão de Foguete",
    "Super Wizard": "Super Mago",
    "Super Dragon": "Super Dragão",
    "Inferno Dragon": "Dragão Infernal",
    "Super Miner": "Super Mineiro",
    "Super Minion": "Super Serva",
    "Super Hog Rider": "Super Corredor",
    "Super Valkyrie": "Super Valquíria",
    "Super Witch": "Super Bruxa",
    "Ice Hound": "Sabueso de Gelo",
    "Super Bowler": "Super Lançador",
    "Raged Barbarian": "Bárbaro Furioso",
    "Sneaky Archer": "Arqueira Furtiva",
    "Boxer Giant": "Gigante Boxeador",
    "Beta Minion": "Serva Beta",
    Bomber: "Bombardeiro",
    "Baby Dragon": "Bebê Dragão",
    "Cannon Cart": "Carrinho de Canhão",
    "Night Witch": "Bruxa da Noite",
    "Drop Ship": "Nau Bombardeira",
    "Super P.E.K.K.A": "Super P.E.K.K.A",
    "Hog Glider": "Deslizador de Porco",
    "Electro Dragon": "Dragão Elétrico",
    Yeti: "Yeti",
    "Dragon Rider": "Dragão Rider",
    "Electro Owl": "Coruja Elétrica",
    "Mighty Yak": "Iaque Poderoso",
    Unicorn: "Unicórnio",
    "Ice Mage": "Mago de Gelo",
    "Skeleton Giant": "Gigante Esqueleto",
    "Skeleton Barrel": "Barril (Esqueleto)",
    "El Primo": "Primo",
    "Royal Ghost": "Mago Real",
    "Royal Dragon": "Dragão Real",
    "Fire Mage": "Mago de Fogo",
    "Fire Dragon": "Dragão de Fogo",
    "Water Mage": "Mago de Água",
    "Water Dragon": "Dragão de Água",
  };