const epIcon = "https://static.wikia.nocookie.net/clashofclans/images";

export const iconUrls = {
  /*============== tropas normais ==============================*/
  Barbarian: `${epIcon}/8/87/Avatar_Barbarian.png`,
  Archer: `${epIcon}/6/68/Avatar_Archer.png`,
  Goblin: `${epIcon}/6/68/Avatar_Goblin.png`,
  Giant: `${epIcon}/7/7d/Avatar_Giant.png`,
  "Wall Breaker": `${epIcon}/3/36/Avatar_Wall_Breaker.png`,
  Balloon: `${epIcon}/8/80/Avatar_Balloon.png`,
  Wizard: `${epIcon}/9/97/Avatar_Wizard.png`,
  Healer: `${epIcon}/9/9c/Avatar_Healer.png`,
  Dragon: `${epIcon}/9/9c/Avatar_Dragon.png`,
  "P.E.K.K.A": `${epIcon}/1/1a/Avatar_P.E.K.K.A.png`,
  Minion: `${epIcon}/6/6d/Avatar_Minion.png`,
  "Hog Rider": `${epIcon}/5/5d/Avatar_Hog_Rider.png`,
  Valkyrie: `${epIcon}/3/39/Avatar_Valkyrie.png`,
  Golem: `${epIcon}/f/f5/Avatar_Golem.png`,
  "Baby Dragon": `${epIcon}/7/7a/Avatar_Baby_Dragon.png`,
  Miner: `${epIcon}/7/7a/Avatar_Miner.png`,
  "Electro Dragon": `${epIcon}/9/97/Avatar_Electro_Dragon.png`,
  Yeti: `${epIcon}/b/be/Avatar_Yeti.png`,
  "Dragon Rider": `${epIcon}/5/50/Avatar_Dragon_Rider.png`,
  "Electro Titan": `${epIcon}/6/67/Avatar_Electro_Titan.png`,
  "Root Rider": `${epIcon}/0/0b/Avatar_Root_Rider.png`,
  Thrower: `${epIcon}/d/da/Avatar_Thrower.png`,
  Minion: `${epIcon}/3/3b/Avatar_Minion.png`,
  "Hog Rider": `${epIcon}/e/e9/Avatar_Hog_Rider.png`,
  Valkyrie: `${epIcon}/3/31/Avatar_Valkyrie.png`,
  Golem: `${epIcon}/4/44/Avatar_Golem.png`,
  Witch: `${epIcon}/9/90/Avatar_Witch.png`,
  "Lava Hound": `${epIcon}/1/1b/Avatar_Lava_Hound.png`,
  Bowler: `${epIcon}/2/24/Avatar_Bowler.png`,
  "Ice Golem": `${epIcon}/7/79/Avatar_Ice_Golem.png`,
  Headhunter: `${epIcon}/8/80/Avatar_Headhunter.png`,
  "Apprentice Warden": `${epIcon}/8/8b/Avatar_Apprentice_Warden.png`,
  Druid: `${epIcon}/4/43/Avatar_Druid.png`,

  "Super Barbarian": `${epIcon}/8/81/Avatar_Super_Barbarian.png/`,
  "Super Archer": `${epIcon}/3/3a/Avatar_Super_Archer.png/`,
  "Super Giant": `${epIcon}/6/6b/Avatar_Super_Giant.png/`,
  "Sneaky Goblin": `${epIcon}/6/6e/Avatar_Sneaky_Goblin.png/`,
  "Super Wall Breaker": `${epIcon}/c/ca/Avatar_Super_Wall_Breaker.png/`,
  "Rocket Balloon": `${epIcon}/e/ed/Avatar_Rocket_Balloon.png/`,
  "Super Wizard": `${epIcon}/f/f9/Avatar_Super_Wizard.png/`,
  /*============== Super tropas ==============================*/
  "Super Dragon": `${epIcon}/0/0f/Avatar_Super_Dragon.png/`,
  "Inferno Dragon": `${epIcon}/0/0b/Avatar_Inferno_Dragon.png/`,
  "Super Miner": `${epIcon}/b/b3/Avatar_Super_Miner.png/`,
  "Super Minion": `${epIcon}/b/be/Avatar_Super_Minion.png/`,
  "Super Hog Rider": `${epIcon}/c/c4/Avatar_Super_Hog_Rider.png/`,
  "Super Valkyrie": `${epIcon}/9/9e/Avatar_Super_Valkyrie.png/`,
  "Super Witch": `${epIcon}/1/18/Avatar_Super_Witch.png/`,
  "Ice Hound": `${epIcon}/b/b0/Avatar_Ice_Hound.png/`,
  "Super Bowler": `${epIcon}/3/39/Avatar_Super_Bowler.png/`,
  /*============== Feitiços - https://clashofclans.fandom.com/wiki/Elixir_Spells - https://clashofclans.fandom.com/wiki/Dark_Spells ================*/
  "Lightning Spell": `${epIcon}/c/c0/Lightning_Spell_info.png`,
  "Healing Spell": `${epIcon}/f/f2/Healing_Spell_info.png`,
  "Rage Spell": `${epIcon}/8/8a/Rage_Spell_info.png`,
  "Jump Spell": `${epIcon}/3/38/Jump_Spell_info.png`,
  "Freeze Spell": `${epIcon}/e/ef/Freeze_Spell_info.png`,
  "Clone Spell": `${epIcon}/9/91/Clone_Spell_info.png`,
  "Invisibility Spell": `${epIcon}/a/a3/Invisibility_Spell_info.png`,
  "Recall Spell": `${epIcon}/7/73/Recall_Spell_info.png`,
  "Revive Spell": `${epIcon}/5/5f/Revive_Spell_info.png`,
  "Poison Spell": `${epIcon}/4/49/Poison_Spell_info.png`,
  "Earthquake Spell": `${epIcon}/3/3f/Earthquake_Spell_info.png`,
  "Haste Spell": `${epIcon}/b/be/Haste_Spell_info.png`,
  "Skeleton Spell": `${epIcon}/0/0f/Skeleton_Spell_info.png`,
  "Bat Spell": `${epIcon}/3/3d/Bat_Spell_info.png`,
  "Overgrowth Spell": `${epIcon}/a/a6/Overgrowth_Spell_info.png`,
  /*============== Máquinas de Cerco ================*/
  "Wall Wrecker": `${epIcon}/f/f3/Avatar_Wall_Wrecker.png/`,
  "Battle Blimp": `${epIcon}/2/2f/Avatar_Battle_Blimp.png/`,
  "Stone Slammer": `${epIcon}/a/ad/Avatar_Stone_Slammer.png/`,
  "Battle Drill": `${epIcon}/9/99/Avatar_Battle_Drill.png/`,
  "Log Launcher": `${epIcon}/7/73/Avatar_Log_Launcher.png/`,
  "Flame Flinger": `${epIcon}/e/e4/Avatar_Flame_Flinger.png/`,
  "Siege Barracks": `${epIcon}/f/fe/Avatar_Siege_Barracks.png/`,
  /*============== Heróis - https://clashofclans.fandom.com/wiki/Heroes ================*/
  "Barbarian King": `${epIcon}/2/26/Avatar_Hero_Barbarian_King.png`,
  "Archer Queen": `${epIcon}/b/b6/Avatar_Hero_Archer_Queen.png`,
  "Minion Prince": `${epIcon}/1/17/Avatar_Hero_Minion_Prince.png`,
  "Grand Warden": `${epIcon}/1/1d/Avatar_Hero_Grand_Warden.png`,
  "Royal Champion": `${epIcon}/8/8e/Avatar_Hero_Royal_Champion.png`,
  "Battle Machine": `${epIcon}/7/7a/Avatar_Hero_Battle_Machine.png`,
  "Battle Copter": `${epIcon}/a/ae/Avatar_Hero_Battle_Copter.png`,
  /*============== Equipamentos do Heróis - https://clashofclans.fandom.com/wiki/Hero_Equipment ================*/
  /*============== PETS ================*/
  "L.A.S.S.I": `${epIcon}/6/62/Avatar_L.A.S.S.I.png`,
  "Electro Owl": `${epIcon}/6/6e/Avatar_Electro_Owl.png`,
  "Mighty Yak": `${epIcon}/0/03/Avatar_Mighty_Yak.png`,
  Unicorn: `${epIcon}/a/ac/Avatar_Unicorn.png`,
  Frosty: `${epIcon}/e/e6/Avatar_Frosty.png`,
  Diggy: `${epIcon}/6/6b/Avatar_Diggy.png`,
  "Poison Lizard": `${epIcon}/a/aa/Avatar_Poison_Lizard.png`,
  Phoenix: `${epIcon}/4/4f/Avatar_Phoenix.png`,
  "Spirit Fox": `${epIcon}/5/52/Avatar_Spirit_Fox.png`,
  "Angry Jelly": `${epIcon}/3/3a/Avatar_Angry_Jelly.png`,
};
